export default {
  Main: "/",
  Home: "/home",
  Mypage: "/mypage",
  SignIn: "/sign-in",
  Login: "/login",
  AcceptTerms: "/accept-terms",
  AcceptTermsDetail: "/accept-terms/detail",
  NotFound: "*",
  SignUpPart1: "/member/sign-up-part1",
  SignUpPart2: "/member/sign-up-part2",
  SignUpPart3: "/member/sign-up-part3",
  SignUpPart4: "/member/sign-up-part4",
  SignUpPart5: "/member/sign-up-part5",
  FindId1: "/find-id1",
  FindId2: "/find-id2",
  FindId3: "/find-id3",
  FindId4: "/find-id4",
  FindId5: "/find-id5",
  FindIdResult: "/find-id/result",
};
